version: "3.8"

services:
  relayer:
    build: ./app
    env_file: .env
    volumes:
      - ./app/:/opt/node_app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
